### ISSUE TITLE
explicitly specify "private" for all private fields.

### ISSUE THREAD

**Issue by dantogno** [JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff#11]
https://github.com/JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff/blob/350a818cb55c8d82a05e4365eb52fa808f92adab/Assets/Scripts/PlayerScripts/MovePlayer.cs#L77

**Comment by DefinitelyNotAShark** [comment]
Done. All private variables and most functions are now declared private if not before
