### ISSUE TITLE
Rename. Don't use abbreviations, or at least complete the thought of what this does.

### ISSUE THREAD

**Issue by dantogno** [JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff#12]
How about `UpdateAnimationParameters()`

https://github.com/JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff/blob/350a818cb55c8d82a05e4365eb52fa808f92adab/Assets/Scripts/PlayerScripts/MovePlayer.cs#L133

**Comment by DefinitelyNotAShark** [comment]
Done
