### ISSUE TITLE
Function names should always be PascalCase

### ISSUE THREAD

**Issue by dantogno** [JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff#18]
https://github.com/JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff/blob/350a818cb55c8d82a05e4365eb52fa808f92adab/Assets/Scripts/PlayerScripts/MovePlayer.cs#L163

**Comment by DefinitelyNotAShark** [comment]
Didn't know that applied to private ones with a non void return type. Done.
