### ISSUE TITLE
I'm not entirely clear what this is for. Add a <summary> comment at the top of the function (just before the function declaration).

### ISSUE THREAD

**Issue by dantogno** [JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff#20]
VS hotkey: ///

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/summary 

https://github.com/JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff/blob/350a818cb55c8d82a05e4365eb52fa808f92adab/Assets/Scripts/PlayerScripts/MovePlayer.cs#L170

**Comment by DefinitelyNotAShark** [comment]
That's fair. It wasn't entirely clear. I added a summary and a couple more comments
