### ISSUE TITLE
What's the jump cooldown for?

### ISSUE THREAD

**Issue by dantogno** [JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff#29]
https://github.com/JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff/blob/350a818cb55c8d82a05e4365eb52fa808f92adab/Assets/Scripts/PlayerScripts/MovePlayer.cs#L237

**Comment by DefinitelyNotAShark** [comment]
Jump cooldown was not needed and has been removed
