### ISSUE TITLE
Move jump to regular Update (not fixed update) to help with responsiveness

### ISSUE THREAD

**Issue by dantogno** [JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff#30]
Adding force over and over across many frames in Update can be bad, but since in theory you only can jump once every so often (because of conditions that govern when jumping is allowed and GetInputDown only returning true first frame button is pressed), it's normally safe and better to do jump in Update.

https://github.com/JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff/blob/350a818cb55c8d82a05e4365eb52fa808f92adab/Assets/Scripts/PlayerScripts/MovePlayer.cs#L115

**Comment by DefinitelyNotAShark** [comment]
Jump has been moved to update. Works just fine in the scenes.
