### ISSUE TITLE
Remove commented out code before committing it to master

### ISSUE THREAD

**Issue by dantogno** [JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff#31]
https://github.com/JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff/blob/350a818cb55c8d82a05e4365eb52fa808f92adab/Assets/Scripts/PlayerScripts/MovePlayer.cs#L257

**Comment by DefinitelyNotAShark** [comment]
All commented out code has been removed except for the hit particle system which we've been going back and forth on.
