### ISSUE TITLE
Do you still need this script? Delete if not.

### ISSUE THREAD

**Issue by dantogno** [JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff#4]
https://github.com/JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff/blob/350a818cb55c8d82a05e4365eb52fa808f92adab/Assets/Sprites/Player%20Sprites/PlayerTestScript/PlayerMovement.cs#L5

**Comment by DefinitelyNotAShark** [comment]
Deleted
