### ISSUE TITLE
camelCase for private fields

### ISSUE THREAD

**Issue by dantogno** [JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff#6]
Please fix them all in this script. 

https://github.com/JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff/blob/350a818cb55c8d82a05e4365eb52fa808f92adab/Assets/Scripts/PlayerScripts/MovePlayer.cs#L12

**Comment by DefinitelyNotAShark** [comment]
Fixed those. Gotta remember to let Will know about that in the future.
