### ISSUE TITLE
What's this comment? Should it be a region? Or a [ToolTip] Or delete it.

### ISSUE THREAD

**Issue by dantogno** [JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff#9]
https://github.com/JWhittom/ITGP-FA18-Cats-and-Fish-Something-Fight-Stuff/blob/350a818cb55c8d82a05e4365eb52fa808f92adab/Assets/Scripts/PlayerScripts/MovePlayer.cs#L52

**Comment by DefinitelyNotAShark** [comment]
Should have been a region. Replaced it.
